### ISSUE TITLE
configurar links do site

### ISSUE THREAD

**Issue by levxyca** [acaverna/acaverna.github.io#8]

**Comment by LelePG** [comment]
O que é pra fazer nos links? Quero fazer :)

**Comment by levxyca** [comment]
É para pegar os ícones que tem no site e adicionar o links da caverna, como as redes sociais por exemplo! Pelo que estou vendo aqui alguém já fez isso e não linkou a issue kkkkk mas vi que tem ali o ícone do discord que está sem o link de convite, se quiser, posso atribuir a você!

**Comment by LelePG** [comment]
Atribui pra mim sim pofavo
:)
